# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Trabajos\8cuatrimestre\compiladores_interpretes\Corte2\algoritmoRecursivo\views\home_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 527)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_texto = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_texto.setGeometry(QtCore.QRect(130, 100, 291, 51))
        self.lineEdit_texto.setStyleSheet("border-radius: 10px;\n"
"border: 1px solid;\n"
"border-color: rgb(0, 0, 0);")
        self.lineEdit_texto.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_texto.setObjectName("lineEdit_texto")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 40, 91, 21))
        self.label.setStyleSheet("font: 75 10pt \"Tahoma\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_verificar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_verificar.setGeometry(QtCore.QRect(230, 210, 101, 41))
        self.pushButton_verificar.setStyleSheet("")
        self.pushButton_verificar.setObjectName("pushButton_verificar")
        self.label_valido = QtWidgets.QLabel(self.centralwidget)
        self.label_valido.setGeometry(QtCore.QRect(240, 330, 81, 16))
        self.label_valido.setStyleSheet("color: rgb(0, 170, 0);\n"
"font: 81 10pt \"Rockwell Extra Bold\";")
        self.label_valido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_valido.setObjectName("label_valido")
        self.label_invalido = QtWidgets.QLabel(self.centralwidget)
        self.label_invalido.setGeometry(QtCore.QRect(220, 330, 131, 16))
        self.label_invalido.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 81 10pt \"Rockwell Extra Bold\";")
        self.label_invalido.setAlignment(QtCore.Qt.AlignCenter)
        self.label_invalido.setObjectName("label_invalido")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GIT ADD"))
        self.pushButton_verificar.setText(_translate("MainWindow", "VERIFICAR"))
        self.label_valido.setText(_translate("MainWindow", "VÁLIDO"))
        self.label_invalido.setText(_translate("MainWindow", "INVÁLIDO"))
